"use client";

export interface NeighborhoodRate {
  name: string;
  price: number;
}

export const NEIGHBORHOOD_RATES: NeighborhoodRate[] = [
  { name: 'Acácio Figueiredo', price: 8.00 },
  { name: 'Alto Branco', price: 10.00 },
  { name: 'Alto da Serra', price: 10.00 },
  { name: 'Aluízio Campos', price: 10.00 },
  { name: 'Araxá', price: 8.00 },
  { name: 'Bela Vista', price: 7.00 },
  { name: 'Bodocongó', price: 7.00 },
  { name: 'C. de Zé Ferreira', price: 10.00 },
  { name: 'Catolé', price: 10.00 },
  { name: 'Centenário', price: 7.00 },
  { name: 'Centro', price: 7.00 },
  { name: 'Cidades', price: 10.00 },
  { name: 'Cinza', price: 7.00 },
  { name: 'Conceição', price: 8.00 },
  { name: 'Cruzeiro', price: 8.00 },
  { name: 'Cuités', price: 10.00 },
  { name: 'D. dos Mecânicos', price: 10.00 },
  { name: 'Dinamérica', price: 7.00 },
  { name: 'Estação Velha', price: 7.00 },
  { name: 'Itararé', price: 10.00 },
  { name: 'J. Continental', price: 10.00 },
  { name: 'J. Paulistano', price: 8.00 },
  { name: 'J. Quarenta', price: 7.00 },
  { name: 'J. Tavares', price: 10.00 },
  { name: 'J. Verdejante', price: 8.00 },
  { name: 'Jeremias', price: 8.00 },
  { name: 'José Pinheiro', price: 10.00 },
  { name: 'Juracy Palhano', price: 12.00 },
  { name: 'Lauritzen', price: 10.00 },
  { name: 'Liberdade', price: 8.00 },
  { name: 'Ligeiro', price: 12.00 },
  { name: 'Louzeiro', price: 8.00 },
  { name: 'Malvinas', price: 7.00 },
  { name: 'Mirante', price: 10.00 },
  { name: 'Monte Castelo', price: 8.00 },
  { name: 'Monte Santo', price: 7.00 },
  { name: 'Nações', price: 12.00 },
  { name: 'Nova Brasília', price: 10.00 },
  { name: 'Nv. Bodocongó', price: 7.00 },
  { name: 'P. Médici', price: 7.00 },
  { name: 'Palmeira', price: 8.00 },
  { name: 'Palmeira Imperial', price: 8.00 },
  { name: 'Pedregal', price: 7.00 },
  { name: 'Portal dos Bosques', price: 7.00 },
  { name: 'Portal Sudoeste', price: 10.00 },
  { name: 'Prata', price: 7.00 },
  { name: 'Ramadinha', price: 7.00 },
  { name: 'Sandra Cavalcante', price: 10.00 },
  { name: 'Santa Cruz', price: 7.00 },
  { name: 'Santa Rosa', price: 7.00 },
  { name: 'Santo Antônio', price: 10.00 },
  { name: 'São José', price: 8.00 },
  { name: 'Serrotão', price: 7.00 },
  { name: 'St. Terezinha', price: 14.00 },
  { name: 'Tambor', price: 10.00 },
  { name: 'Três Irmãs', price: 8.00 },
  { name: 'Universitário', price: 7.00 },
  { name: 'Velame', price: 10.00 },
  { name: 'Vila C. Branco', price: 10.00 },
  { name: 'Vila Cabral', price: 12.00 }
];